# -*- coding: utf-8 -*-
"""
Regenerates miniapp/data.js from the bot's data/*.json files, so the chat
bot and the mini app always quiz from the same content.

Run after editing anything in data/:
    python tools/build_miniapp.py
CI fails if data.js is out of date (python tools/build_miniapp.py --check).
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "data")
OUT = os.path.join(ROOT, "miniapp", "data.js")

VOCAB_FIELDS = ("id", "de", "uz", "gender", "pos")


def load(name):
    with open(os.path.join(DATA, name), encoding="utf-8") as f:
        return json.load(f)


def build():
    vocab = load("vocabulary_data.json")
    grammar_qs = load("grammar_questions.json")
    grammar_ref = load("grammar_data.json")

    vocab_by_lek = {
        str(l["lektion"]): [{k: item.get(k) for k in VOCAB_FIELDS} for item in l["items"]]
        for l in vocab["lessons"]
    }
    grammar_by_lek = {str(l["lektion"]): l["questions"] for l in grammar_qs["lessons"]}
    titles = {str(l["lektion"]): l["title"] for l in grammar_ref.get("lessons", []) if l.get("title")}

    def dump(obj):
        return json.dumps(obj, ensure_ascii=False, separators=(",", ":"))

    return (
        "/* Generated by tools/build_miniapp.py from data/*.json. Do not edit by hand. */\n"
        f"window.VOCAB_DATA = {dump(vocab_by_lek)};\n"
        f"window.GRAMMAR_DATA = {dump(grammar_by_lek)};\n"
        f"window.LEKTION_TITLES = {dump(titles)};\n"
    )


def main():
    content = build()
    if "--check" in sys.argv:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current != content:
            print("miniapp/data.js is out of date. Run: python tools/build_miniapp.py")
            sys.exit(1)
        print("miniapp/data.js is up to date.")
        return
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    print(f"Wrote {os.path.relpath(OUT, ROOT)} ({len(content) // 1024} KB)")


if __name__ == "__main__":
    main()
